[tool.poetry]
name = "AnkiPy"
version = "0.1.0"
description = "Create anki decks and cards from your Python application"
authors = ["patarapolw <patarapolw@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.7"
